// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useEffect, useState } from "react";
import { ScreenVariantProvider } from "../../components/plasmic/dapp_rta_vote/PlasmicGlobalVariant__Screen";
import { PlasmicBallot } from "../../components/plasmic/dapp_rta_vote/PlasmicBallot";
import { useRouter } from "next/router";
import { getPollTitle, vote } from "../../contracts";

function Ballot() {
  const router = useRouter();
  const contractAddr = router.query.tx?.toString();
  const [pollTitle, setPollTitle] = useState("");
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    if (!contractAddr) {
      return;
    }
    getPollTitle(contractAddr).then(setPollTitle);
  }, [contractAddr]);
  const genVote = (ballot: number) => ({
    async onClick() {
      if (loading) return;
      setLoading(true);
      try {
        const vtx = await vote(contractAddr, ballot);
        debugger;
        await vtx.wait();
      } catch (e) {
        alert(e.message);
        console.error(e);
      } finally {
        setLoading(false);
      }
    },
    loading,
  });
  return <PlasmicBallot title={pollTitle} aye={genVote(1)} nay={genVote(-1)} />;
}

export default Ballot;
