// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7CKZhD2BVpe8oYNyjz4EUo
// Component: CYSztTUGQI
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import StackPage from "../../StackPage"; // plasmic-import: 4Bd4Yhsd_bl/component
import Input from "../../Input"; // plasmic-import: 8ig3uWjRld/component
import Button from "../../Button"; // plasmic-import: sdZdmGowFd/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_dapp_rta_vote.module.css"; // plasmic-import: 7CKZhD2BVpe8oYNyjz4EUo/projectcss
import * as sty from "./PlasmicShare.module.css"; // plasmic-import: CYSztTUGQI/css

export type PlasmicShare__VariantMembers = {};

export type PlasmicShare__VariantsArgs = {};
type VariantPropType = keyof PlasmicShare__VariantsArgs;
export const PlasmicShare__VariantProps = new Array<VariantPropType>();

export type PlasmicShare__ArgsType = {};
type ArgPropType = keyof PlasmicShare__ArgsType;
export const PlasmicShare__ArgProps = new Array<ArgPropType>();

export type PlasmicShare__OverridesType = {
  root?: p.Flex<"div">;
  stackPage?: p.Flex<typeof StackPage>;
  shareUrl?: p.Flex<typeof Input>;
  goToVote?: p.Flex<typeof Button>;
};

export interface DefaultShareProps {
  dataFetches: PlasmicShare__Fetches;
}

function PlasmicShare__RenderFunc(props: {
  variants: PlasmicShare__VariantsArgs;
  args: PlasmicShare__ArgsType;
  overrides: PlasmicShare__OverridesType;
  dataFetches?: PlasmicShare__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Share"}</title>
        <meta key="og:title" property="og:title" content={"Share"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <StackPage
            data-plasmic-name={"stackPage"}
            data-plasmic-override={overrides.stackPage}
            className={classNames("__wab_instance", sty.stackPage)}
          >
            <div
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.box__rWrqi
              )}
            >
              {"Vote created"}
            </div>

            <Input
              data-plasmic-name={"shareUrl"}
              data-plasmic-override={overrides.shareUrl}
              className={classNames("__wab_instance", sty.shareUrl)}
              title={
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box___0MqVt
                  )}
                >
                  {"Share contract below"}
                </div>
              }
            />

            <div className={classNames(defaultcss.all, sty.box__cbJ0Q)}>
              <div className={classNames(defaultcss.all, sty.box___4GXFy)}>
                <Button
                  data-plasmic-name={"goToVote"}
                  data-plasmic-override={overrides.goToVote}
                  className={classNames("__wab_instance", sty.goToVote)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___7Shz6
                    )}
                  >
                    {"Go to vote page"}
                  </div>
                </Button>
              </div>
            </div>
          </StackPage>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "stackPage", "shareUrl", "goToVote"],
  stackPage: ["stackPage", "shareUrl", "goToVote"],
  shareUrl: ["shareUrl"],
  goToVote: ["goToVote"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  stackPage: typeof StackPage;
  shareUrl: typeof Input;
  goToVote: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShare__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShare__VariantsArgs;
    args?: PlasmicShare__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicShare__Fetches;
  } & Omit<PlasmicShare__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicShare__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicShare__ArgProps,
      internalVariantPropNames: PlasmicShare__VariantProps,
    });

    const { dataFetches } = props;

    return PlasmicShare__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShare";
  } else {
    func.displayName = `PlasmicShare.${nodeName}`;
  }
  return func;
}

export const PlasmicShare = Object.assign(
  // Top-level PlasmicShare renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    stackPage: makeNodeComponent("stackPage"),
    shareUrl: makeNodeComponent("shareUrl"),
    goToVote: makeNodeComponent("goToVote"),

    // Metadata about props expected for PlasmicShare
    internalVariantProps: PlasmicShare__VariantProps,
    internalArgProps: PlasmicShare__ArgProps,
  }
);

export default PlasmicShare;
/* prettier-ignore-end */
