// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7CKZhD2BVpe8oYNyjz4EUo
// Component: vVq_ENM8si
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import StackPage from "../../StackPage"; // plasmic-import: 4Bd4Yhsd_bl/component
import Button from "../../Button"; // plasmic-import: sdZdmGowFd/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_dapp_rta_vote.module.css"; // plasmic-import: 7CKZhD2BVpe8oYNyjz4EUo/projectcss
import * as sty from "./PlasmicBallot.module.css"; // plasmic-import: vVq_ENM8si/css

export type PlasmicBallot__VariantMembers = {};

export type PlasmicBallot__VariantsArgs = {};
type VariantPropType = keyof PlasmicBallot__VariantsArgs;
export const PlasmicBallot__VariantProps = new Array<VariantPropType>();

export type PlasmicBallot__ArgsType = {
  title?: React.ReactNode;
};

type ArgPropType = keyof PlasmicBallot__ArgsType;
export const PlasmicBallot__ArgProps = new Array<ArgPropType>("title");

export type PlasmicBallot__OverridesType = {
  root?: p.Flex<"div">;
  stackPage?: p.Flex<typeof StackPage>;
  aye?: p.Flex<typeof Button>;
  nay?: p.Flex<typeof Button>;
};

export interface DefaultBallotProps {
  dataFetches: PlasmicBallot__Fetches;
}

function PlasmicBallot__RenderFunc(props: {
  variants: PlasmicBallot__VariantsArgs;
  args: PlasmicBallot__ArgsType;
  overrides: PlasmicBallot__OverridesType;
  dataFetches?: PlasmicBallot__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Vote"}</title>
        <meta key="og:title" property="og:title" content={"Vote"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <StackPage
            data-plasmic-name={"stackPage"}
            data-plasmic-override={overrides.stackPage}
            className={classNames("__wab_instance", sty.stackPage)}
          >
            <div className={classNames(defaultcss.all, sty.box__swEav)}>
              {p.renderPlasmicSlot({
                defaultContents: "Poll title",
                value: args.title,
                className: classNames(sty.slotTitle),
              })}
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box___5DQvx)}
            >
              <Button
                data-plasmic-name={"aye"}
                data-plasmic-override={overrides.aye}
                className={classNames("__wab_instance", sty.aye)}
                color={"primary" as const}
              >
                {"Aye"}
              </Button>

              <Button
                data-plasmic-name={"nay"}
                data-plasmic-override={overrides.nay}
                className={classNames("__wab_instance", sty.nay)}
                color={"secondary" as const}
              >
                {"Nay"}
              </Button>
            </p.Stack>
          </StackPage>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "stackPage", "aye", "nay"],
  stackPage: ["stackPage", "aye", "nay"],
  aye: ["aye"],
  nay: ["nay"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  stackPage: typeof StackPage;
  aye: typeof Button;
  nay: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBallot__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBallot__VariantsArgs;
    args?: PlasmicBallot__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicBallot__Fetches;
  } & Omit<PlasmicBallot__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBallot__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBallot__ArgProps,
      internalVariantPropNames: PlasmicBallot__VariantProps,
    });

    const { dataFetches } = props;

    return PlasmicBallot__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBallot";
  } else {
    func.displayName = `PlasmicBallot.${nodeName}`;
  }
  return func;
}

export const PlasmicBallot = Object.assign(
  // Top-level PlasmicBallot renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    stackPage: makeNodeComponent("stackPage"),
    aye: makeNodeComponent("aye"),
    nay: makeNodeComponent("nay"),

    // Metadata about props expected for PlasmicBallot
    internalVariantProps: PlasmicBallot__VariantProps,
    internalArgProps: PlasmicBallot__ArgProps,
  }
);

export default PlasmicBallot;
/* prettier-ignore-end */
