// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7CKZhD2BVpe8oYNyjz4EUo
// Component: tl3mxo0fWy
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_dapp_rta_vote.module.css"; // plasmic-import: 7CKZhD2BVpe8oYNyjz4EUo/projectcss
import * as sty from "./PlasmicBigIconButton.module.css"; // plasmic-import: tl3mxo0fWy/css

export type PlasmicBigIconButton__VariantMembers = {};

export type PlasmicBigIconButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicBigIconButton__VariantsArgs;
export const PlasmicBigIconButton__VariantProps = new Array<VariantPropType>();

export type PlasmicBigIconButton__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};

type ArgPropType = keyof PlasmicBigIconButton__ArgsType;
export const PlasmicBigIconButton__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicBigIconButton__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
};

export interface DefaultBigIconButtonProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  className?: string;
}

function PlasmicBigIconButton__RenderFunc(props: {
  variants: PlasmicBigIconButton__VariantsArgs;
  args: PlasmicBigIconButton__ArgsType;
  overrides: PlasmicBigIconButton__OverridesType;
  dataFetches?: PlasmicBigIconButton__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, sty.box)}
      >
        {p.renderPlasmicSlot({
          defaultContents: null,
          value: args.children,
        })}
      </div>

      {p.renderPlasmicSlot({
        defaultContents: "wallet name",
        value: args.slot,
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBigIconButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBigIconButton__VariantsArgs;
    args?: PlasmicBigIconButton__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicBigIconButton__Fetches;
  } & Omit<PlasmicBigIconButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBigIconButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBigIconButton__ArgProps,
      internalVariantPropNames: PlasmicBigIconButton__VariantProps,
    });

    const { dataFetches } = props;

    return PlasmicBigIconButton__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBigIconButton";
  } else {
    func.displayName = `PlasmicBigIconButton.${nodeName}`;
  }
  return func;
}

export const PlasmicBigIconButton = Object.assign(
  // Top-level PlasmicBigIconButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicBigIconButton
    internalVariantProps: PlasmicBigIconButton__VariantProps,
    internalArgProps: PlasmicBigIconButton__ArgProps,
  }
);

export default PlasmicBigIconButton;
/* prettier-ignore-end */
