// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7CKZhD2BVpe8oYNyjz4EUo
// Component: JHk19r9QqJ
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import TabPage from "../../TabPage"; // plasmic-import: bnO-AW974wUz/component
import Input from "../../Input"; // plasmic-import: 8ig3uWjRld/component
import Button from "../../Button"; // plasmic-import: sdZdmGowFd/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_dapp_rta_vote.module.css"; // plasmic-import: 7CKZhD2BVpe8oYNyjz4EUo/projectcss
import * as sty from "./PlasmicVote.module.css"; // plasmic-import: JHk19r9QqJ/css

export type PlasmicVote__VariantMembers = {};

export type PlasmicVote__VariantsArgs = {};
type VariantPropType = keyof PlasmicVote__VariantsArgs;
export const PlasmicVote__VariantProps = new Array<VariantPropType>();

export type PlasmicVote__ArgsType = {};
type ArgPropType = keyof PlasmicVote__ArgsType;
export const PlasmicVote__ArgProps = new Array<ArgPropType>();

export type PlasmicVote__OverridesType = {
  root?: p.Flex<"div">;
  tabPage?: p.Flex<typeof TabPage>;
  contractAddr?: p.Flex<typeof Input>;
  box?: p.Flex<"div">;
  next?: p.Flex<typeof Button>;
};

export interface DefaultVoteProps {
  dataFetches: PlasmicVote__Fetches;
}

function PlasmicVote__RenderFunc(props: {
  variants: PlasmicVote__VariantsArgs;
  args: PlasmicVote__ArgsType;
  overrides: PlasmicVote__OverridesType;
  dataFetches?: PlasmicVote__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Vote"}</title>
        <meta key="og:title" property="og:title" content={"Vote"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={""}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <TabPage
            data-plasmic-name={"tabPage"}
            data-plasmic-override={overrides.tabPage}
            className={classNames("__wab_instance", sty.tabPage)}
            tab={"_1" as const}
          >
            <Input
              data-plasmic-name={"contractAddr"}
              data-plasmic-override={overrides.contractAddr}
              className={classNames("__wab_instance", sty.contractAddr)}
              placeholder={"0x..." as const}
              title={"Vote Contract Address"}
            />

            <div
              data-plasmic-name={"box"}
              data-plasmic-override={overrides.box}
              className={classNames(defaultcss.all, sty.box)}
            >
              <Button
                data-plasmic-name={"next"}
                data-plasmic-override={overrides.next}
                className={classNames("__wab_instance", sty.next)}
              >
                {"Next"}
              </Button>
            </div>
          </TabPage>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "tabPage", "contractAddr", "box", "next"],
  tabPage: ["tabPage", "contractAddr", "box", "next"],
  contractAddr: ["contractAddr"],
  box: ["box", "next"],
  next: ["next"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  tabPage: typeof TabPage;
  contractAddr: typeof Input;
  box: "div";
  next: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVote__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVote__VariantsArgs;
    args?: PlasmicVote__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicVote__Fetches;
  } & Omit<PlasmicVote__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicVote__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicVote__ArgProps,
      internalVariantPropNames: PlasmicVote__VariantProps,
    });

    const { dataFetches } = props;

    return PlasmicVote__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVote";
  } else {
    func.displayName = `PlasmicVote.${nodeName}`;
  }
  return func;
}

export const PlasmicVote = Object.assign(
  // Top-level PlasmicVote renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tabPage: makeNodeComponent("tabPage"),
    contractAddr: makeNodeComponent("contractAddr"),
    box: makeNodeComponent("box"),
    next: makeNodeComponent("next"),

    // Metadata about props expected for PlasmicVote
    internalVariantProps: PlasmicVote__VariantProps,
    internalArgProps: PlasmicVote__ArgProps,
  }
);

export default PlasmicVote;
/* prettier-ignore-end */
