// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { useRouter } from "next/router";
import * as React from "react";
import { PlasmicIndex } from "../components/plasmic/dapp_rta_vote/PlasmicIndex";
import {
  prepareMetaMask,
  prepareRPC,
  prepareWalletConnect,
} from "../contracts";

function Index() {
  const router = useRouter();
  const genConn = (fn: () => Promise<void>): any =>
    ({
      async onClick() {
        try {
          await fn();
          router.push(`/start`);
        } catch (e) {
          alert(e.message);
          console.error(e);
        }
      },
    } as any);
  return (
    <PlasmicIndex
      connWc={genConn(prepareWalletConnect)}
      connMm={genConn(prepareMetaMask)}
      connRpc={genConn(prepareRPC)}
    />
  );
}

export default Index;
