// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { useRouter } from "next/router";
import React, { useState } from "react";
import { ScreenVariantProvider } from "../components/plasmic/dapp_rta_vote/PlasmicGlobalVariant__Screen";
import { PlasmicStart } from "../components/plasmic/dapp_rta_vote/PlasmicStart";
import { deployPollContract } from "../contracts";

function Start() {
  const [title, setTitle] = useState("");
  const [deadline, setDeadline] = useState(
    Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 7
  );
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  return (
    <PlasmicStart
      title={
        {
          text: {
            onInput(e: any) {
              setTitle(e.target.value);
            },
            value: title,
          },
        } as any
      }
      deadline={
        {
          text: {
            onInput(e: any) {
              setDeadline(e.target.value);
            },
            value: deadline,
          },
        } as any
      }
      next={
        {
          async onClick() {
            if (loading) return;
            setLoading(true);
            try {
              const tx = await deployPollContract(title, deadline);
              await tx.deployTransaction.wait();
              const addr = tx.address;
              router.push(`/share/${addr}`);
            } catch (e) {
              console.error(e);
              alert(e.message);
            } finally {
              setLoading(false);
            }
          },
          loading,
        } as any
      }
    />
  );
}

export default Start;
