// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import React, { useState } from "react";
import Input from "../components/Input";
import { PlasmicVote } from "../components/plasmic/dapp_rta_vote/PlasmicVote";
import { deployPollContract } from "../contracts";
import { useRouter } from "next/router";
function Vote() {
  const router = useRouter();
  const [contractAddr, setContractAddr] = useState("");
  return (
    <PlasmicVote
      contractAddr={
        {
          text: {
            onInput: (e: any) => {
              e.currentTarget.value !== undefined &&
                setContractAddr(e.currentTarget.value);
            },
            value: contractAddr,
          },
        } as any
      }
      next={
        {
          onClick: () => {
            if (!/^0x[0-9A-Fa-f]{40}$/.test(contractAddr)) {
              alert("Invalid contract address");
              return;
            }
            router.push("/ballot/" + contractAddr);
          },
        } as any
      }
    />
  );
}

export default Vote;
