// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import { useRouter } from "next/router";
import * as React from "react";
import { ScreenVariantProvider } from "../../components/plasmic/dapp_rta_vote/PlasmicGlobalVariant__Screen";
import { PlasmicShare } from "../../components/plasmic/dapp_rta_vote/PlasmicShare";

function Share() {
  const router = useRouter();
  const tx = router.query.tx?.toString();
  return (
    <PlasmicShare
      shareUrl={{ text: { value: tx } }}
      goToVote={{
        onClick() {
          router.replace(`/ballot/${tx}`);
        },
      }}
    />
  );
}

export default Share;
